name: reftest222

on: [push, pull_request]

jobs:
  reftest:
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Set up Homebrew only for macOS
        if: runner.os == 'macOS'
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: brew install only for macOS
        if: runner.os == 'macOS'
        run: |
          brew install python-setuptools
      - name: Use npm@8
        run: npm i -g npm@8 --registry=https://registry.npmjs.org
      - name: Run test
        run: |
          npm ci
          npm run build
          npm test